# $NetBSD$
#
# editors/emacs28 が pkgsrc から消えたので、消される直前の版をここへ引き取った。
#
#	CVS	pkgsrc/editors/emacs28  Makefile,v 1.54
#	削除	2026-08-25 17:33:15 UTC  wiz  commitid UIVD8ABupUq3M2TG
#
# PKGREVISION は CVS の最終値 47 に +1 した 48 で固定する。ここに手を入れても
# 動かさない。上流の値より大きければ pkgin が入れ替えるので、それ以上に
# 上げる意味が無い。同じ番号で入れ直すときは make replace を使う。
#
# emacs28-nox11 の側は 1 になる。上流の editors/emacs28-nox11 は
# PKGREVISION を持たず (0)、その +1 だからで、48 と揃わないのはもとの二つが
# 揃っていなかったためである。番号はそれぞれの Makefile に書いてある。
#
# 上流と違うところ:
#
#   - MAINTAINER をこちらへ移した。上流に居ないものを pkgsrc-users 宛のまま
#     置いておくと、報告先が無い
#   - $NetBSD$ は潰した。ここは CVS ではないので、あの番号は更新されない
#   - EMACS_COEXIST を足した (下記)
#   - CVE の当て物を足した。詳しくは patches/ の各ヘッダ
#
#
# pkgsrc の脆弱性 DB (pkg-vulnerabilities) は版で照合するので、当てても
# emacs28-28.2 は CVE-2022-45939 などで警告され続ける。DB に「当てた」を
# 伝える口が無いためで、消すには ALLOW_VULNERABLE_PACKAGES を立てるしか
# なく、それは他の本当の穴まで黙らせる。警告は出るままにしてある。
#
# 実際に当ててあるのは patches/ の各ヘッダに書いたとおり、
#
#	CVE-2022-45939  etags     lib-src/etags.c
#	CVE-2022-48337  ctags     lib-src/etags.c
#	CVE-2022-48338  ruby-mode lisp/progmodes/ruby-mode.el
#	CVE-2022-48339  htmlfontify
#	CVE-2023-27986  emacsclient-mail.desktop
#	CVE-2024-30202  org-macro
#	CVE-2024-30203  gnus mm-view
#	CVE-2024-30204  org latex preview
#	CVE-2024-30205  org remote file
#	CVE-2024-39331  org link abbrev
#	CVE-2024-53920  elisp-mode
#
# の 11 件と、CVE の付いていない assertion 系 5 件。
# used by zakinko/emacs28/Makefile
# used by zakinko/emacs28-nox11/Makefile

.include "../../mk/bsd.prefs.mk"

DISTNAME=	emacs-${EMACS_VERSION}
PKGNAME?=	${DISTNAME:S/emacs/emacs28/}
CATEGORIES=	zakinko editors
MASTER_SITES=	${MASTER_SITE_GNU:=emacs/}
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	zakinko@snowrabbit.org
HOMEPAGE=	https://www.gnu.org/software/emacs/
COMMENT=	GNU editing macros (editor)
LICENSE=	gnu-gpl-v3

WRKSRC=		${WRKDIR}/${DISTNAME:S/b$//}

# use makeinfo from pkgsrc/deve/gtexinfo
TEXINFO_REQD=	4.13

GNU_CONFIGURE=	yes
INFO_FILES=	yes
USE_TOOLS+=	autoconf gmake gzip makeinfo gm4 gsed

REPLACE_SH+=	autogen.sh

CONFIGURE_ARGS+=	--srcdir=${WRKSRC}
CONFIGURE_ARGS+=	--localstatedir=${VARBASE}
CONFIGURE_ARGS+=	--disable-autodepend
CONFIGURE_ENV+=		GAMEOWN=${GAMES_USER}

USE_GAMESGROUP=		yes

BUILD_DEFS+=		VARBASE
BUILD_DEFS+=		GAMEDATAMODE
PLIST_SRC+=		../../zakinko/emacs28/PLIST

#
# EMACS_COEXIST
#	yes にすると無印の bin/emacs を入れず、bin/emacs28 のように版付きの
#	名前だけを置く。zakinko の emacs22 から emacs28 を並べて入れられる
#	ようになる。
#
#	その代わり、この版に対して elisp パッケージは建たなくなる。
#	emacs/modules.mk が
#
#		EMACS_BIN= ${PREFIX}/bin/${_EMACS_FLAVOR}
#
#	と、版によらず ${PREFIX}/bin/emacs で決め打ちしているためで、無印を
#	置かない以上どうにもならない。日本語入力の検査のように elisp を建てる
#	用途は既定の no 側で行う。
#
#	既定は no。そのときは上流とまったく同じものが入る。PKG_OPTIONS には
#	しない。PKG_OPTIONS_VAR が全 emacs 版で共有の PKG_OPTIONS.emacs な
#	ので、そこに知らない名前が入ると上流の emacs30 などが
#	bsd.options.mk の PKG_FAIL_REASON で建たなくなる。
#
#	info は 63 本あっていずれも無印なので、共存時は --infodir ごと
#	${PKGINFODIR}/emacs28 へ振る。desktop、icons、metainfo、
#	emacs-module.h、systemd の unit、site-lisp/subdirs.el は版で分ける
#	すべが無いため、共存時は入れない。
#
EMACS_COEXIST?=		no
BUILD_DEFS+=		EMACS_COEXIST

PLIST_VARS+=		plain coexist
.if ${EMACS_COEXIST} == "yes"
PLIST.coexist=		yes
EMACS_INFOSUB=		emacs28/
# CONFIGURE_ARGS には足さない。pkgsrc が gnu-configure.mk で
# --infodir=${GNU_CONFIGURE_INFODIR} を後ろに足すので、そちらが勝つ。
GNU_CONFIGURE_INFODIR=	${PREFIX}/${PKGINFODIR}/emacs28

post-install: coexist-names

.PHONY: coexist-names
coexist-names:
	cd ${DESTDIR}${PREFIX}/bin && \
		${RM} -f emacs && \
		${MV} emacs-${EMACS_VERSION} emacs28 && \
		${MV} emacsclient emacsclient28 && \
		${MV} ctags emacs28-ctags && \
		${MV} etags emacs28-etags && \
		${MV} ebrowse emacs28-ebrowse
	# Emacs の install-man は入れた man をその場で gzip する。configure の
	# compress-install は既定で on なので、post-install の時点で在るのは
	# emacs.1 ではなく emacs.1.gz になる。素の名前だけを mv すると
	# "No such file or directory" で落ちる。pkgsrc があとで .1 へ戻すので、
	# 改名しない既定の形では誰も踏まない。両方の綴りを見る。
	cd ${DESTDIR}${PREFIX}/${PKGMANDIR}/man1 && \
	for m in emacs:emacs28 emacsclient:emacsclient28 \
		 ctags:emacs28-ctags etags:emacs28-etags \
		 ebrowse:emacs28-ebrowse; do \
		o=$${m%%:*}; n=$${m\#*:}; \
		for e in "" .gz; do \
			[ -f "$$o.1$$e" ] || continue; \
			${MV} "$$o.1$$e" "$$n.1$$e"; \
		done; \
	done
	${RM} -rf ${DESTDIR}${PREFIX}/share/applications
	${RM} -rf ${DESTDIR}${PREFIX}/share/icons
	${RM} -rf ${DESTDIR}${PREFIX}/share/metainfo
	${RM} -rf ${DESTDIR}${PREFIX}/lib/systemd
	${RM} -f  ${DESTDIR}${PREFIX}/include/emacs-module.h
	${RM} -f  ${DESTDIR}${PREFIX}/share/emacs/site-lisp/subdirs.el
.else
PLIST.plain=		yes
EMACS_INFOSUB=		# 無印のまま
.endif
PLIST_SUBST+=		EMACS_INFOSUB=${EMACS_INFOSUB:Q}

.include "../../zakinko/emacs28/version.mk"

BUILD_TARGET=		bootstrap
EMACS_VERSION=		${_EMACS_VERSION_MAJOR}.${_EMACS_VERSION_MINOR}
PLIST_SUBST+=		EMACS_VERSION=${EMACS_VERSION}

MAKE_DIRS_PERMS+=	${VARBASE}/games/emacs ${GAMES_USER} ${GAMES_GROUP} ${GAMEDIRMODE}
CONF_FILES_PERMS+=	/dev/null ${VARBASE}/games/emacs/snake-scores \
			${GAMES_USER} ${GAMES_GROUP} ${GAMEDATAMODE}
CONF_FILES_PERMS+=	/dev/null ${VARBASE}/games/emacs/tetris-scores \
			${GAMES_USER} ${GAMES_GROUP} ${GAMEDATAMODE}

SPECIAL_PERMS+=		libexec/emacs/${EMACS_VERSION}/${MACHINE_GNU_PLATFORM}/update-game-score ${SETGID_GAMES_PERMS}

# build PATH in the dumped emacs is not a problem
CHECK_WRKREF_SKIP+=	bin/emacs
CHECK_WRKREF_SKIP+=	bin/emacs-${EMACS_VERSION}
CHECK_WRKREF_SKIP+=	libexec/emacs/${PKGVERSION_NOREV}/${MACHINE_GNU_PLATFORM}/emacs.pdmp

PRINT_PLIST_AWK+=	{ gsub(/${MACHINE_GNU_PLATFORM}/, "$${MACHINE_GNU_PLATFORM}"); }

.if (${OPSYS} == "NetBSD") && \
    !exists(/usr/lib/libgcc_s.so) && !exists(/usr/lib/libgcc.a)
# NetBSD with native Clang doesn't provide libgcc, everything is in libc.
pre-configure: fake-libgcc

.PHONY: fake-libgcc
fake-libgcc:
	${AR} q ${BUILDLINK_DIR}/lib/libgcc.a
.endif

.if (${OPSYS} == "NetBSD") && exists(/usr/include/term.h)
CPPFLAGS+=	-DTERMINFO
.elif ${OPSYS} == "FreeBSD" || ${OPSYS} == "Linux" || ${OPSYS} == "OpenBSD"
.include "../../mk/curses.buildlink3.mk"
.else
.include "../../mk/termcap.buildlink3.mk"
.endif

.include "../../mk/oss.buildlink3.mk"

post-extract:
	cp ${.CURDIR}/../../zakinko/emacs28/files/site-init.el ${WRKSRC}/lisp
	${CHMOD} -R go-w ${WRKSRC}

.include "../../devel/libgetopt/buildlink3.mk"
