# $NetBSD$

# used by inputmethod/mozc-elisp333/Makefile
# used by inputmethod/mozc-renderer333/Makefile
# used by inputmethod/mozc-server333/Makefile
# used by inputmethod/mozc-tool333/Makefile

# 3.33.6089 is the last mozc that carries GYP.  The next tag, 3.33.6133, has
# neither src/build_mozc.py nor src/gyp/ -- they were removed on 2026-03-11
# ("Remove files for GYP build.").  So this is the newest mozc that can be
# built where bazel cannot run, and that will not change.

DISTNAME=	mozc-3.33.6089
CATEGORIES=	inputmethod
MASTER_SITES=	${MASTER_SITE_GITHUB:=google/}
GITHUB_PROJECT=	mozc
GITHUB_TAG=	${PKGVERSION_NOREV}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/google/mozc/
COMMENT=	Japanese inputmethod Mozc engine
LICENSE=	modified-bsd

GITHUB_SUBMODULES+=	google breakpad 216cea7bca53fa441a3ee0d0f5fd339a3a894224 third_party/breakpad
GITHUB_SUBMODULES+=	google googletest 52eb8108c5bdec04579160ae17225d66034bd723 third_party/gtest
GITHUB_SUBMODULES+=	chromium gyp 9ecf45e37677743503342ee4c6a76eaee80e4a7f third_party/gyp
GITHUB_SUBMODULES+=	hiroyuki-komatsu japanese-usage-dictionary e5b3425575734c323e1d947009dd74709437b684 third_party/japanese_usage_dictionary
GITHUB_SUBMODULES+=	protocolbuffers protobuf 4fbd1111a292d04746c732573025e3251de0bb9c third_party/protobuf
GITHUB_SUBMODULES+=	abseil abseil-cpp 987c57f325f7fa8472fa84e1f885f7534d391b0d third_party/abseil-cpp
GITHUB_SUBMODULES+=	microsoft wil fc5dbf55989fe20351c71d038a8d12de4b397a6d third_party/wil

DISTFILES+=	${DEFAULT_DISTFILES}

EXTRACT_ONLY=	${DEFAULT_DISTFILES} ${_GITHUB_DEFAULT_DISTFILES}

MOZC_DISTS+=	dictionary.png
SITES.dictionary.png=	-https://raw.githubusercontent.com/google/material-design-icons/4.0.0/png/action/chrome_reader_mode/materialiconsoutlined/48dp/1x/outline_chrome_reader_mode_black_48dp.png

MOZC_DISTS+=	dictionary.svg
SITES.dictionary.svg=	-https://raw.githubusercontent.com/google/material-design-icons/4.0.0/src/action/chrome_reader_mode/materialiconsoutlined/24px.svg

MOZC_DISTS+=	properties.png
SITES.properties.png=	-https://raw.githubusercontent.com/google/material-design-icons/4.0.0/png/action/settings/materialiconsround/48dp/1x/round_settings_black_48dp.png

MOZC_DISTS+=	properties.svg
SITES.properties.svg=	-https://raw.githubusercontent.com/google/material-design-icons/4.0.0/src/action/settings/materialiconsround/24px.svg

MOZC_DISTS+=	tool.png
SITES.tool.png=	-https://raw.githubusercontent.com/google/material-design-icons/4.0.0/png/action/build/materialicons/48dp/1x/baseline_build_black_48dp.png

MOZC_DISTS+=	tool.svg
SITES.tool.svg=	-https://raw.githubusercontent.com/google/material-design-icons/4.0.0/src/action/build/materialicons/24px.svg

MOZC_DISTS+=	ken_all.zip
SITES.ken_all.zip=	https://www.post.japanpost.jp/zipcode/dl/kogaki/zip/

MOZC_DISTS+=	jigyosyo.zip
SITES.jigyosyo.zip=	https://www.post.japanpost.jp/zipcode/dl/jigyosyo/zip/

.for d in ${MOZC_DISTS}
DISTFILES+=	${d}
.endfor

WRKSRC=		${WRKDIR}/${DISTNAME}/src

DISTINFO_FILE=	${.CURDIR}/../../inputmethod/mozc-server333/distinfo
PATCHDIR=	${.CURDIR}/../../inputmethod/mozc-server333/patches

PYTHON_VERSIONS_INCOMPATIBLE+=	27

.include "../../mk/bsd.prefs.mk"

.if empty(PKG_OPTIONS:Mgyp)
# 3.33's .bazeliskrc pins USE_BAZEL_VERSION=8.4.1, but carrying a second
# bazel just for this package costs more than moving the dependencies
# forward.  devel/bazel9 is the 9.2.0 that mozc 3.34 needs anyway, so
# both versions build with the one tool.
#
# The rules_cc 0.2.2 that 3.33 pins reads the CcInfo, DebugPackageInfo and
# CcSharedLibraryInfo globals bazel 9 removed, which stops the build in the
# loading phase; patch-MODULE.bazel raises it to 0.2.17 and adds what
# upstream added in 3.34 for bazel 9.  Measured on NetBSD 11.0/amd64:
# server:mozc_server builds, 2125 actions, no errors.
TOOL_DEPENDS+=	bazel>=9.0.0:../../devel/bazel9
# 3.33 replaced WORKSPACE.bazel with MODULE.bazel.  bzlmod resolves its
# dependencies while building, so lining up tarballs under --distdir the way
# the 2.29 packages do does not close the build.
ALLOW_NETWORK_ACCESS=	yes
.else
TOOL_DEPENDS+=	${PYPKGPREFIX}-gyp>=0.1pre20200512.caa60026e223fc501e8b337fd5086ece4028b1c6:../../devel/gyp
TOOL_DEPENDS+=	${PYPKGPREFIX}-six-[0-9]*:../../lang/py-six
TOOL_DEPENDS+=	ninja-build-[0-9]*:../../devel/ninja-build
.endif

USE_LANGUAGES=	c c++
USE_TOOLS+=	pkg-config unzip

USE_CXX_FEATURES+=	c++20

SUBST_CLASSES+=		prefix
SUBST_STAGE.prefix=	pre-configure
SUBST_MESSAGE.prefix=	Setting PREFIX
SUBST_FILES.prefix+=	base/process.cc
SUBST_FILES.prefix+=	base/system_util.cc
SUBST_VARS.prefix+=	PREFIX
SUBST_VARS.prefix+=	X11BASE

OPSYSVARS+=	OSDEST
.if empty(PKG_OPTIONS:Mgyp)
OSDEST.Linux=	linux-opt
OSDEST.NetBSD=	netbsd-opt
.else
OSDEST.Linux=	linux
OSDEST.NetBSD=	bsd

MOZC_BUILD_MODE?=	Release

do-configure:
	cd ${WRKSRC} && ${SETENV} ${MAKE_ENV} \
		${PYTHONBIN} build_mozc.py gyp \
			--gypdir=${LOCALBASE}/bin \
			${MOZC_GYP_ARGS}
.endif

CHECK_PIE_SUPPORTED=	no
pre-configure:
	${MKDIR} ${WRKSRC}/dist
.for d in ${MOZC_DISTS}
	${LN} -s ${DISTDIR}/${d} ${WRKSRC}/dist/${d}
.endfor
	${RM} -r ${WRKDIR}/.cwrapper

# mozc-server and mozc-elisp link neither Qt nor GL.  Including these
# unconditionally records qt6-qtbase as a run-time dependency and sets
# USE_X11, and a machine without X11 then cannot even fetch the package.
# Only mozc-renderer and mozc-tool need them.
.if !empty(PKGPATH:M*/mozc-renderer333) || !empty(PKGPATH:M*/mozc-tool333)
.include "../../graphics/MesaLib/buildlink3.mk"
.include "../../x11/qt6-qtbase/buildlink3.mk"
.endif

.include "../../lang/python/tool.mk"
.include "../../mk/atomic64.mk"
