# $NetBSD: Makefile.common,v 1.3 2023/08/14 05:13:31 wiz Exp $
#
# used by editors/emacs29/Makefile
# used by editors/emacs29-nox11/Makefile

.include "../../mk/bsd.prefs.mk"

DISTNAME=	emacs-${EMACS_VERSION}
PKGNAME?=	${DISTNAME:S/emacs/emacs29/}
CATEGORIES=	editors
MASTER_SITES=	${MASTER_SITE_GNU:=emacs/}
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://www.gnu.org/software/emacs/
COMMENT=	GNU editing macros (editor)
LICENSE=	gnu-gpl-v3

WRKSRC=		${WRKDIR}/${DISTNAME:S/b$//}

# use makeinfo from pkgsrc/deve/gtexinfo
TEXINFO_REQD+=	4.13

GNU_CONFIGURE=	yes
INFO_FILES=	yes
USE_TOOLS+=	autoconf gmake gzip makeinfo gm4 gsed

REPLACE_SH+=	autogen.sh

CONFIGURE_ARGS+=	--srcdir=${WRKSRC}
CONFIGURE_ARGS+=	--localstatedir=${VARBASE}
CONFIGURE_ARGS+=	--disable-autodepend
CONFIGURE_ENV+=		GAMEOWN=${GAMES_USER}

USE_GAMESGROUP=		yes

BUILD_DEFS+=		VARBASE
BUILD_DEFS+=		GAMEDATAMODE
# The nox build installs under its own EMACS_TAG, so its file list is
# not the X one; it brings its own PLIST.  EMACS_TAG is only set this
# early by a package that overrides it.
.if defined(EMACS_TAG)
PLIST_SRC+=		${.CURDIR}/PLIST
.else
PLIST_SRC+=		../../netbsd-i386-3e/emacs29-A/PLIST
.endif

.include "../../netbsd-i386-3e/emacs29-A/version.mk"

BUILD_TARGET=		bootstrap
EMACS_VERSION=		${_EMACS_VERSION_MAJOR}.${_EMACS_VERSION_MINOR}
PLIST_SUBST+=		EMACS_VERSION=${EMACS_VERSION}
PLIST_VARS+=		native nonative

MAKE_DIRS_PERMS+=	${VARBASE}/games/emacs ${GAMES_USER} ${GAMES_GROUP} ${GAMEDIRMODE}
CONF_FILES_PERMS+=	/dev/null ${VARBASE}/games/emacs/snake-scores \
			${GAMES_USER} ${GAMES_GROUP} ${GAMEDATAMODE}
CONF_FILES_PERMS+=	/dev/null ${VARBASE}/games/emacs/tetris-scores \
			${GAMES_USER} ${GAMES_GROUP} ${GAMEDATAMODE}

SPECIAL_PERMS+=		${_EMACS_ARCHLIB}/update-game-score ${SETGID_GAMES_PERMS}

# build PATH in the dumped emacs is not a problem
CHECK_WRKREF_SKIP+=	bin/emacs
CHECK_WRKREF_SKIP+=	bin/emacs-${EMACS_TAG}
CHECK_WRKREF_SKIP+=	${_EMACS_ARCHLIB}/${_EMACS_PDMP}

PRINT_PLIST_AWK+=	{ gsub(/${MACHINE_GNU_PLATFORM}/, "$${MACHINE_GNU_PLATFORM}"); }

.if (${OPSYS} == "NetBSD") && \
    !exists(/usr/lib/libgcc_s.so) && !exists(/usr/lib/libgcc.a)
# NetBSD with native Clang doesn't provide libgcc, everything is in libc.
pre-configure: fake-libgcc

.PHONY: fake-libgcc
fake-libgcc:
	${AR} q ${BUILDLINK_DIR}/lib/libgcc.a
.endif

.if (${OPSYS} == "NetBSD") && exists(/usr/include/term.h)
CPPFLAGS+=	-DTERMINFO
.elif ${OPSYS} == "FreeBSD" || ${OPSYS} == "Linux" || ${OPSYS} == "OpenBSD"
.include "../../mk/curses.buildlink3.mk"
.else
.include "../../mk/termcap.buildlink3.mk"
.endif

.include "../../mk/oss.buildlink3.mk"

post-extract:
	cp ${.CURDIR}/../../netbsd-i386-3e/emacs29-A/files/site-init.el ${WRKSRC}/lisp
	${CHMOD} -R go-w ${WRKSRC}

.include "../../devel/libgetopt/buildlink3.mk"

# Let several Emacsen live in one prefix; see emacs30-A/Makefile.common
# for the layout.  EMACS_TAG is the version for the X build and adds
# -nox11 for the nox one, which then keeps its own datadir and libexecdir.
EMACS_TAG?=		${EMACS_VERSION}
CONFIGURE_ARGS+=	--program-transform-name='s/$$/-${EMACS_TAG}/'
CONFIGURE_ARGS+=	--includedir=${PREFIX}/include/emacs-${EMACS_TAG}
.if ${EMACS_TAG} != ${EMACS_VERSION}
_EMACS_DATADIR=		share/emacs-${EMACS_TAG}
_EMACS_LIBEXEC=		libexec/emacs-${EMACS_TAG}
CONFIGURE_ARGS+=	--datadir=${PREFIX}/${_EMACS_DATADIR}
CONFIGURE_ARGS+=	--libexecdir=${PREFIX}/${_EMACS_LIBEXEC}
.else
_EMACS_DATADIR=		share
_EMACS_LIBEXEC=		libexec
.endif
_EMACS_ARCHLIB=		${_EMACS_LIBEXEC}/emacs/${PKGVERSION_NOREV}/${MACHINE_GNU_PLATFORM}
GNU_CONFIGURE_INFODIR=	${PREFIX}/${_EMACS_DATADIR}/emacs/${EMACS_VERSION}/info

# Emacs 29 and later look for <argv0>.pdmp and stop there; 27 and 28
# also try emacs.pdmp.  The transform makes argv0 emacs-${EMACS_TAG}, so
# a dump named emacs.pdmp is never found and every start loads the whole
# of lisp from source (loadup.el).
_EMACS_PDMP=		emacs-${EMACS_TAG}.pdmp

INFO_FILES=		# the info files are private to this Emacs now
PLIST_SUBST+=		EMACS_TAG=${EMACS_TAG}
FILES_SUBST+=		EMACS_TAG=${EMACS_TAG}
PRINT_PLIST_AWK+=	{ gsub(/${EMACS_TAG}/, "$${EMACS_TAG}"); }
PRINT_PLIST_AWK+=	{ gsub(/${EMACS_VERSION}/, "$${EMACS_VERSION}"); }

post-install:
	${RM} -f ${DESTDIR}${PREFIX}/${_EMACS_DATADIR}/emacs/site-lisp/subdirs.el
	cd ${DESTDIR}${PREFIX}/${_EMACS_ARCHLIB} && \
		${MV} emacs.pdmp ${_EMACS_PDMP}
