# $NetBSD$

DISTNAME=	libndp-1.9
CATEGORIES=	zakinko net
MASTER_SITES=	http://libndp.org/files/

MAINTAINER=	cirnatdan@NetBSD.org
HOMEPAGE=	http://libndp.org/
COMMENT=	Library for IPv6 Neighbor Discovery Protocol
LICENSE=	gnu-lgpl-v2.1

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes

PKGCONFIG_OVERRIDE+=	libndp/libndp.pc.in

.include "../../mk/bsd.pkg.mk"
