# $NetBSD$

# emacs25-nox11 とは CONFLICTS しない。nox 版は EMACS_TAG の下に入り、
# path を一つも共有しない。

PKGREVISION=	38
.include "../../netbsd-i386-3e/emacs25-A/Makefile.common"

.include "options.mk"

.include "../../graphics/hicolor-icon-theme/buildlink3.mk"
.include "../../sysutils/desktop-file-utils/desktopdb.mk"
.include "../../mk/bsd.pkg.mk"
