# $NetBSD$

# emacs26-nox11 とは CONFLICTS しない。nox 版は EMACS_TAG の下に入り、
# path を一つも共有しない。

.include "../../netbsd-i386-3e/emacs26-A/Makefile.common"

PKGREVISION=	63

.include "options.mk"

.include "../../graphics/hicolor-icon-theme/buildlink3.mk"
.include "../../sysutils/desktop-file-utils/desktopdb.mk"
.include "../../mk/bsd.pkg.mk"
