# $NetBSD$

PKGREVISION=	46

# emacs22-nox11 とは CONFLICTS しない。nox 版は EMACS_TAG の下に入り、
# path を一つも共有しない。

.include "options.mk"

.include "../../netbsd-i386-3e/emacs22-A/Makefile.common"
.include "../../mk/bsd.pkg.mk"
