;; run in the p30 Emacs after run 6: exercise the patched packages
(defvar ex-results nil)
(defmacro ex (name &rest body)
  `(push (cons ,name (condition-case e (progn ,@body) (error (format "ERR %S" e)))) ex-results))
(let ((sl (expand-file-name "share/emacs/site-lisp" (getenv "PREFIX"))))
  (dolist (d (directory-files sl t "^[^.]"))
    (when (file-directory-p d) (add-to-list 'load-path d))))
(ex "deferred:process-shell" (progn (require 'deferred) (let ((d (deferred:process-shell "echo" "hello" "world"))) (deferred:sync! d))))
(ex "bongo mpv args" (progn (require 'bongo) (require 'bongo-mpv nil t) (let ((f (or (and (fboundp 'bongo-mpv-remote-args) 'bongo-mpv-remote-args) (and (fboundp 'bongo--mpv-remote-args) 'bongo--mpv-remote-args)))) (if f (funcall f "/tmp/sock") (mapconcat #'symbol-name (seq-filter (lambda (s) (string-match "mpv.*remote\\|remote.*mpv" (symbol-name s))) (apropos-internal "mpv")) " ")))))
(ex "dropdown-list selection face inherits a real face" (progn (require 'dropdown-list) (let ((i (face-attribute 'dropdown-list-selection-face :inherit))) (list i (facep i)))))
(ex "erobot interactive spec" (progn (require 'erobot) (interactive-form 'erobot)))
(ex "icicles loads" (progn (require 'icicles) (featurep 'icicles)))
(ex "regress loads" (progn (require 'regress) (fboundp 'regress)))
(ex "remember loads" (progn (require 'remember) (fboundp 'remember-finalize)))
(ex "rnc-mode loads" (progn (require 'rnc-mode) (fboundp 'rnc-mode)))
(ex "teco loads" (progn (require 'teco) (fboundp 'teco-command)))
(ex "uboat loads" (progn (require 'uboat) (fboundp 'uboat-death-message)))
(ex "xrdb-mode loads" (progn (require 'xrdb-mode) (fboundp 'xrdb-mode)))
(ex "wikipedia-mode loads with outline-magic" (progn (require 'wikipedia-mode) (fboundp 'outline-cycle)))
(ex "atomic-chrome save binding" (progn (require 'atomic-chrome) (key-description (car (where-is-internal 'atomic-chrome-close-current-buffer atomic-chrome-edit-mode-map)))))
(ex "ledger-mode loads" (progn (require 'ledger-mode) (fboundp 'ledger-mode)))
(ex "rpm-spec-mode loads" (progn (require 'rpm-spec-mode) (fboundp 'rpm-spec-mode)))
(ex "all-the-icons data" (progn (require 'all-the-icons) (all-the-icons-icon-for-file "foo.el")))
(ex "nerd-icons data" (progn (require 'nerd-icons) (nerd-icons-icon-for-file "foo.el")))
(ex "emojify data" (progn (require 'emojify) (emojify-set-emoji-data) (hash-table-count emojify-emojis)))
(ex "package-lint data" (progn (require 'package-lint) (with-temp-buffer (insert ";;; foo.el --- x -*- lexical-binding: t -*-\n;; Package-Requires: ((emacs \"24\"))\n") (emacs-lisp-mode) (length (package-lint-buffer)))))
(ex "dashboard banner path" (progn (require 'dashboard) (file-exists-p (expand-file-name "emacs.png" dashboard-banners-directory))))
(ex "treemacs icons+scripts" (progn (require 'treemacs) (list (file-exists-p (expand-file-name "icons/default/dir-closed.png" treemacs-dir)) (file-exists-p (expand-file-name "src/scripts/treemacs-git-status.py" treemacs-dir)))))
(ex "systemd directives" (progn (require 'systemd) (length systemd-unit-directives)))
(ex "geiser-guile src" (progn (require 'geiser-guile) (file-exists-p (expand-file-name "geiser/emacs.scm" geiser-guile-scheme-dir))))
(ex "julia-repl loads (source only)" (progn (require 'julia-repl) (fboundp 'julia-repl)))
(ex "zenburn theme" (progn (require 'zenburn-theme) (memq 'zenburn (custom-available-themes))))
(dolist (r (reverse ex-results)) (message "%-45s %S" (car r) (cdr r)))
