# $NetBSD$

CONFLICTS+=	emacs25-nox11-[0-9]*

PKGREVISION=	38
.include "../../zakinko/emacs25/Makefile.common"

.include "options.mk"

.include "../../graphics/hicolor-icon-theme/buildlink3.mk"
.include "../../sysutils/desktop-file-utils/desktopdb.mk"
.include "../../mk/bsd.pkg.mk"
