# $NetBSD$

BUILDLINK_TREE+=	emacs20-compat

.if !defined(EMACS20_COMPAT_BUILDLINK3_MK)
EMACS20_COMPAT_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.emacs20-compat+=	${EMACS_PKGNAME_PREFIX}emacs20-compat>=20260922
BUILDLINK_PKGSRCDIR.emacs20-compat?=	../../devel/emacs20-compat

BUILDLINK_CONTENTS_FILTER.emacs20-compat=	${EGREP} '.*\.el$$|.*\.elc$$'
.endif # EMACS20_COMPAT_BUILDLINK3_MK

BUILDLINK_TREE+=	-emacs20-compat
