# $NetBSD: Makefile.common,v 1.23 2025/03/13 18:44:01 maya Exp $
#
# used by zakinko/emacs21/Makefile
# used by zakinko/emacs21-nox11/Makefile

DISTNAME=	emacs-${EMACSVERSION}a
PKGNAME?=	emacs21-${EMACSVERSION}a

MASTER_SITES=	${MASTER_SITE_GNU:=emacs/}
MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://www.gnu.org/software/emacs/emacs.html
COMMENT=	GNU editing macros (editor)
# src/COPYING in the 21.4a tarball is the GNU GPL, "Version 2, June 1991".
LICENSE=	gnu-gpl-v2

# configure: error: Emacs hasn't been ported to `x86_64-apple-darwin17' systems.
BROKEN_ON_PLATFORM=	Darwin-*-*

# += , not =.  Both Makefiles that include this one state their conflict with
# the other before the include:
#
#	emacs21/Makefile:6		CONFLICTS+=	emacs21-nox11-[0-9]*
#	emacs21-nox11/Makefile:8	CONFLICTS+=	emacs21-[0-9]*
#
# and a plain = here threw that away, so neither package declared the other.
# They install the same bin/emacs and the same share/emacs/21.4, so pkg_add
# would let the second one overwrite the first.  editors/emacs22's
# Makefile.common already uses += for the same reason.
CONFLICTS+=	mule-[0-9]*

USE_TOOLS+=		gmake perl:run
GNU_CONFIGURE=		yes

PATCHDIR=	${.CURDIR}/../../zakinko/emacs21/patches
FILESDIR=	${.CURDIR}/../../zakinko/emacs21/files
DISTINFO_FILE=	${.CURDIR}/../../zakinko/emacs21/distinfo
PLIST_SRC=	${.CURDIR}/../../zakinko/emacs21/PLIST

# needed for 21.4a, can probably go away on next update
EMACSVERSION=	21.4
WRKSRC=		${WRKDIR}/emacs-${EMACSVERSION}
PLIST_SUBST+=	EMACSVERSION=${EMACSVERSION:Q}

MAKEFLAGS+=	EMACSLOADPATH=${WRKSRC}/lisp

# build PATH in the dumped emacs is not a problem
CHECK_WRKREF_SKIP+=	bin/emacs
CHECK_WRKREF_SKIP+=	bin/emacs-${EMACSVERSION}

CONFIGURE_ARGS+=	--srcdir=${WRKSRC}
INSTALL_MAKE_FLAGS+=	prefix=${DESTDIR}${PREFIX}
INSTALL_MAKE_FLAGS+=	mandir=${DESTDIR}${PREFIX}/${PKGMANDIR}
INSTALL_MAKE_FLAGS+=	infodir=${DESTDIR}${PREFIX}/${PKGINFODIR}

.include "../../mk/bsd.prefs.mk"

# If using GNU ld 2.13.2.1 or later, avoid creating combined reloc
# sections and .data reloc sections, both of which Emacs can't handle
# properly.  Analyzed by Stephen Ma.
LDFLAGS+=	-Wl,-z,nocombreloc

# Use terminfo on NetBSD-6.
# We cannot use terminfo.*.mk as emacs WILL force a link to termcap,
# but this is fine for us.
.if (${OPSYS} == "NetBSD") && exists(/usr/include/term.h)
CPPFLAGS+=	-DTERMINFO
.endif

.if (${OPSYS} == "DragonFly") && exists(/usr/lib/crtn.o)
CPPFLAGS+=	-DDFLY_CRT_USRLIB
.endif

# pkglint: a PLIST identifier may not contain a dot.  It happened to work
# because make accepts the dot in a variable name, but the name is meant to
# be a plain word.
PLIST_VARS+=	fns
.if ${OPSYS} == "Darwin"
PLIST_SUBST+=	DOCTAIL=""
.else
PLIST.fns=	yes
PLIST_SUBST+=	DOCTAIL="-${EMACSVERSION}.1"
.endif

# Disable W^X.
LDFLAGS.OpenBSD+=	-Z

.include "../../mk/compiler.mk"
.if !empty(CC_VERSION:Mgcc-3.*)
CFLAGS+=	-fno-zero-initialized-in-bss
.endif
.if !empty(PKGSRC_COMPILER:Mgcc)
CFLAGS+=	-Wno-error=implicit-int
CFLAGS+=	-Wno-error=implicit-function-declaration
CFLAGS+=	-Wno-error=incompatible-pointer-types
.endif

.if !empty(PKGSRC_COMPILER:Mclang)
TOOL_DEPENDS+=	tradcpp-[0-9]*:../../devel/tradcpp
TRADCPP=	${PREFIX}/bin/tradcpp
.else
TRADCPP=	${CPP} -traditional-cpp
.endif
ALL_ENV+=	TRADCPP=${TRADCPP:Q}

.if (${OPSYS} == "NetBSD") && \
    !exists(/usr/lib/libgcc_s.so) && !exists(/usr/lib/libgcc.a)
# NetBSD with native Clang doesn't provide libgcc, everything is in libc.
pre-configure: fake-libgcc
.PHONY: fake-libgcc
fake-libgcc:
	${AR} q ${BUILDLINK_DIR}/lib/libgcc.a
.endif

INFO_FILES=	yes
REPLACE_PERL=	lib-src/grep-changelog

post-extract:
	${CP} ${FILESDIR}/site-init.el ${WRKSRC}/lisp
	${CP} ${FILESDIR}/amd64.h ${WRKSRC}/src/m
	${CP} ${FILESDIR}/powermac.h ${WRKSRC}/src/m
	${CP} ${FILESDIR}/darwin.h ${WRKSRC}/src/s
	${CP} ${FILESDIR}/dragonfly.h ${WRKSRC}/src/s
	${CP} ${FILESDIR}/unexmacosx.c ${WRKSRC}/src
	${CP} ${FILESDIR}/sh3el.h ${WRKSRC}/src/m

# for patch-ba
post-build:
	cd ${WRKSRC}/lisp && \
	   rm sort.elc && ${MAKE_PROGRAM} sort.elc && \
	   rm mail/smtpmail.elc && ${MAKE_PROGRAM} mail/smtpmail.elc && \
	   rm fast-lock.elc && ${MAKE_PROGRAM} fast-lock.elc

pre-install:
	${RUN} ${FIND} ${WRKSRC} -type f -name "*.orig" -exec ${RM} -f {} +

post-install:
	${CHOWN} -R ${SHAREOWN}:${SHAREGRP} ${DESTDIR}${PREFIX}/share/emacs
	${CHMOD} -R go-w ${DESTDIR}${PREFIX}/share/emacs

# Emacs reads site-lisp/site-start.el at startup, before ~/.emacs, because
# site-run-file is "site-start" and site-lisp is on load-path.  pkgsrc has had
# no such file, so every elisp package told the user to paste autoloads into
# their own .emacs by hand.  This one loads whatever packages left in
# site-lisp/site-start.d, so they can register themselves instead.
post-install: site-start
.PHONY: site-start
site-start:
	${INSTALL_DATA} ${FILESDIR}/site-start.el \
		${DESTDIR}${PREFIX}/share/emacs/site-lisp/site-start.el
