# $NetBSD$
#
# editors/emacs26 が pkgsrc から消えたので、消される直前の版をここへ引き取った。
#
#	CVS	pkgsrc/editors/emacs26  Makefile,v 1.75
#	削除	2026-08-25 17:33:12 UTC  wiz  commitid UIVD8ABupUq3M2TG  (rev 1.76, state dead)
#
# PKGREVISION は CVS の最終値 62 に +1 した 63 で固定する。ここに手を入れても
# 動かさない。上流の値より大きければ pkgin が入れ替えるので、それ以上に
# 上げる意味が無い。同じ番号で入れ直すときは make replace を使う。
#
# emacs26-nox11 の側は 2 になる。上流のあちらは別に PKGREVISION を持って
# いて、その最終値 1 に +1 したもの。番号が揃わないのは、もとの二つが
# 揃っていなかったためである。
#
# 上流と違うところ:
#
#   - MAINTAINER をこちらへ移した。上流に居ないものを pkgsrc-users 宛のまま
#     置いておくと、報告先が無い
#   - $NetBSD$ は潰した。ここは CVS ではないので、あの番号は更新されない
#   - EMACS_COEXIST を足した
#   - 脆弱性の当て物を足した。何を当てたかは patches/ の各ヘッダにある
#
# used by zakinko/emacs26/Makefile
# used by zakinko/emacs26-nox11/Makefile


MKPIE_SUPPORTED=        no

.include "../../mk/bsd.prefs.mk"

DISTNAME=	emacs-${EMACS_VERSION}
PKGNAME?=	${DISTNAME:S/emacs/emacs26/}
CATEGORIES=	zakinko editors
MASTER_SITES=	${MASTER_SITE_GNU:=emacs/}

MAINTAINER=	zakinko@snowrabbit.org
HOMEPAGE=	https://www.gnu.org/software/emacs/
COMMENT=	GNU editing macros (editor)
LICENSE=	gnu-gpl-v3

WRKSRC=		${WRKDIR}/${DISTNAME:S/b$//}

GNU_CONFIGURE=	yes
INFO_FILES=	yes
USE_TOOLS+=	autoconf automake gmake gzip makeinfo gm4 gsed

CONFIGURE_ARGS+=	--srcdir=${WRKSRC}
CONFIGURE_ARGS+=	--localstatedir=${VARBASE}
CONFIGURE_ARGS+=	--disable-autodepend
CONFIGURE_ENV+=		GAMEOWN=${GAMES_USER}

USE_GAMESGROUP=		yes

BUILD_DEFS+=		VARBASE
BUILD_DEFS+=		GAMEDATAMODE
PLIST_SRC+=		../../zakinko/emacs26/PLIST

.include "../../zakinko/emacs26/version.mk"

#
# EMACS_COEXIST
#	yes にすると無印の bin/emacs を入れず、bin/emacs26 のように版付きの
#	名前だけを置く。zakinko の emacs22 から emacs28 を並べて入れられる。
#
#	その代わり、この版に対して elisp パッケージは建たなくなる。
#	emacs/modules.mk が EMACS_BIN を ${PREFIX}/bin/emacs と版によらず
#	決め打ちしているためで、無印を置かない以上どうにもならない。日本語
#	入力の検査のように elisp を建てる用途は既定の no 側で行う。
#
#	既定は no。そのときは上流とまったく同じものが入る。PKG_OPTIONS には
#	しない。PKG_OPTIONS_VAR が全 emacs 版で共有の PKG_OPTIONS.emacs な
#	ので、そこに知らない名前が入ると bsd.options.mk の PKG_FAIL_REASON で
#	上流の emacs30 などが建たなくなる。
#
#	info はいずれも無印なので、共存時は --infodir ごと
#	${PKGINFODIR}/emacs26 へ振る。desktop や icons のように版で分ける
#	すべが無いものは、共存時は入れない。
#
EMACS_COEXIST?=		no
BUILD_DEFS+=		EMACS_COEXIST

PLIST_VARS+=		plain coexist
.if ${EMACS_COEXIST} == "yes"
PLIST.coexist=		yes
EMACS_INFOSUB=		emacs26/
# CONFIGURE_ARGS には足さない。pkgsrc が gnu-configure.mk で
# --infodir=${GNU_CONFIGURE_INFODIR} を後ろに足すので、そちらが勝つ。
GNU_CONFIGURE_INFODIR=	${PREFIX}/${PKGINFODIR}/emacs26

post-install: coexist-names

.PHONY: coexist-names
coexist-names:
	cd ${DESTDIR}${PREFIX}/bin && \
		${MV} ctags emacs26-ctags && \
		${MV} ebrowse emacs26-ebrowse && \
		${MV} emacs-${PKGVERSION_NOREV} emacs26 && \
		${MV} emacsclient emacsclient26 && \
		${MV} etags emacs26-etags
	# Emacs の install-man は入れた man をその場で gzip する。configure の
	# compress-install は既定で on なので、post-install の時点で在るのは
	# emacs.1 ではなく emacs.1.gz になる。素の名前だけを mv すると
	# "No such file or directory" で落ちる。pkgsrc があとで .1 へ戻すので、
	# 改名しない既定の形では誰も踏まない。両方の綴りを見る。
	cd ${DESTDIR}${PREFIX}/${PKGMANDIR}/man1 && \
	for m in ctags:emacs26-ctags ebrowse:emacs26-ebrowse emacs:emacs26 \
		 emacsclient:emacsclient26 etags:emacs26-etags; do \
		o=$${m%%:*}; n=$${m\#*:}; \
		for e in "" .gz; do \
			[ -f "$$o.1$$e" ] || continue; \
			${MV} "$$o.1$$e" "$$n.1$$e"; \
		done; \
	done
	${RM} -rf ${DESTDIR}${PREFIX}/lib/systemd
	${RM} -rf ${DESTDIR}${PREFIX}/share/applications
	${RM} -rf ${DESTDIR}${PREFIX}/share/icons
	${RM} -rf ${DESTDIR}${PREFIX}/share/metainfo
	${RM} -f  ${DESTDIR}${PREFIX}/bin/emacs
	${RM} -f  ${DESTDIR}${PREFIX}/include/emacs-module.h
	${RM} -f  ${DESTDIR}${PREFIX}/share/emacs/site-lisp/subdirs.el
${RM} -f  ${DESTDIR}${PREFIX}/share/emacs/site-lisp/site-start.el
.else
PLIST.plain=		yes
EMACS_INFOSUB=		# 無印のまま
.endif
PLIST_SUBST+=		EMACS_INFOSUB=${EMACS_INFOSUB:Q}

BUILD_TARGET=		bootstrap
EMACS_VERSION=		${_EMACS_VERSION_MAJOR}.${_EMACS_VERSION_MINOR}
PLIST_SUBST+=		EMACS_VERSION=${EMACS_VERSION}

MAKE_DIRS_PERMS+=	${VARBASE}/games/emacs ${GAMES_USER} ${GAMES_GROUP} ${GAMEDIRMODE}
CONF_FILES_PERMS+=	/dev/null ${VARBASE}/games/emacs/snake-scores \
			${GAMES_USER} ${GAMES_GROUP} ${GAMEDATAMODE}
CONF_FILES_PERMS+=	/dev/null ${VARBASE}/games/emacs/tetris-scores \
			${GAMES_USER} ${GAMES_GROUP} ${GAMEDATAMODE}

SPECIAL_PERMS+=		libexec/emacs/${EMACS_VERSION}/${MACHINE_GNU_PLATFORM}/update-game-score ${SETGID_GAMES_PERMS}

# build PATH in the dumped emacs is not a problem
CHECK_WRKREF_SKIP+=	bin/emacs
CHECK_WRKREF_SKIP+=	bin/emacs-${EMACS_VERSION}

PRINT_PLIST_AWK+=	{ gsub(/${MACHINE_GNU_PLATFORM}/, "$${MACHINE_GNU_PLATFORM}"); }

.if (${OPSYS} == "NetBSD") && \
    !exists(/usr/lib/libgcc_s.so) && !exists(/usr/lib/libgcc.a)
# NetBSD with native Clang doesn't provide libgcc, everything is in libc.
pre-configure: fake-libgcc

.PHONY: fake-libgcc
fake-libgcc:
	${AR} q ${BUILDLINK_DIR}/lib/libgcc.a
.endif

.if (${OPSYS} == "NetBSD") && exists(/usr/include/term.h)
CPPFLAGS+=	-DTERMINFO
.elif ${OPSYS} == "FreeBSD" || ${OPSYS} == "Linux" || ${OPSYS} == "OpenBSD"
.include "../../mk/curses.buildlink3.mk"
.else
.include "../../mk/termcap.buildlink3.mk"
.endif

.include "../../mk/oss.buildlink3.mk"

post-extract:
	cp ${.CURDIR}/../../zakinko/emacs26/files/site-init.el ${WRKSRC}/lisp
	${CHMOD} -R go-w ${WRKSRC}

.include "../../devel/libgetopt/buildlink3.mk"

# Emacs reads site-lisp/site-start.el at startup, before ~/.emacs, because
# site-run-file is "site-start" and site-lisp is on load-path.  pkgsrc has had
# no such file, so every elisp package told the user to paste autoloads into
# their own .emacs by hand.  This one loads whatever packages left in
# site-lisp/site-start.d, so they can register themselves instead.
.if ${EMACS_COEXIST} != "yes"
post-install: site-start
.PHONY: site-start
site-start:
	${INSTALL_DATA} ${FILESDIR}/site-start.el \
		${DESTDIR}${PREFIX}/share/emacs/site-lisp/site-start.el
.endif
