# $NetBSD$

CONFLICTS+=	emacs26-nox11-[0-9]*

.include "../../zakinko/emacs26/Makefile.common"

PKGREVISION=	63

.include "options.mk"

.include "../../graphics/hicolor-icon-theme/buildlink3.mk"
.include "../../sysutils/desktop-file-utils/desktopdb.mk"
.include "../../mk/bsd.pkg.mk"
