# $NetBSD: Makefile.common,v 1.31 2026/02/19 15:09:47 wiz Exp $
#
# 上流 pkgsrc の textproc/libxml2/Makefile.common の写しに、DISTNAME を
# 2.15.1 から 2.15.3 へ上げただけのもの。
#
# 2.15.2 (2026-03-03) が CVE-2025-8732, CVE-2026-0989, CVE-2026-0990,
# CVE-2026-0992, CVE-2026-1757 を直している。pkgsrc が追いついていない
# だけなので、doc/upstream/ の diff を送って取り込まれたらここは消すこと。
#
# used by textproc/libxml2/Makefile
# used by textproc/py-libxml2/Makefile

DISTNAME=	libxml2-2.15.3
CATEGORIES=	textproc
MASTER_SITES=	${MASTER_SITE_GNOME:=sources/libxml2/${PKGVERSION_NOREV:R}/}
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://gitlab.gnome.org/GNOME/libxml2/-/wikis/home

DISTINFO_FILE=	${.CURDIR}/../../textproc/libxml2/distinfo
PATCHDIR=	${.CURDIR}/../../textproc/libxml2/patches
