# $NetBSD$

CONFLICTS+=	emacs27-nox11-[0-9]*

PKGREVISION=	59
.include "../../zakinko/emacs27/Makefile.common"

.include "options.mk"

.include "../../graphics/hicolor-icon-theme/buildlink3.mk"
.include "../../sysutils/desktop-file-utils/desktopdb.mk"
.include "../../fonts/harfbuzz/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
