# $NetBSD$

PKGNAME=	emacs20-nox11-20.7
PKGREVISION=	28

# No CONFLICTS: with EMACS_TAG carrying the variant, this build shares
# no path with the X one.
EMACS_TAG=	20.7-nox11

FILESDIR=	${.CURDIR}/../../netbsd-i386-3e/emacs20-A/files
PATCHDIR=	${.CURDIR}/../../netbsd-i386-3e/emacs20-A/patches
PKGDIR=		${.CURDIR}/../../editors/emacs20
DISTINFO_FILE=	${.CURDIR}/../../netbsd-i386-3e/emacs20-A/distinfo
PLIST_SRC=	${.CURDIR}/PLIST

.include "../../netbsd-i386-3e/emacs20-A/Makefile"
